server:
  port: 8000

spring:
  redis:
    database: 0
    host: redis
    port: 6379

info:
  application:
    name: "myapp"
    author: "Li Lin"

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    git:
      enabled: true
      mode: simple
    java:
      enabled: true

  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
